In [25]:
import pandas as pd

In [26]:
titanic_df=pd.read_csv("F:\github\Data preprocessing\Titanic_data.csv")

<>:1: SyntaxWarning: "\g" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\g"? A raw string is also an option.
<>:1: SyntaxWarning: "\g" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\g"? A raw string is also an option.
C:\Users\User\AppData\Local\Temp\ipykernel_31972\3966130584.py:1: SyntaxWarning: "\g" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\g"? A raw string is also an option.
  titanic_df=pd.read_csv("F:\github\Data preprocessing\Titanic_data.csv")

In [27]:
titanic_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [28]:
titanic_df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [29]:
df=pd.read_csv("World Largest Cities by Population 2024.csv")

In [30]:
#data structure list,dict,tuple and set
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 801 entries, 0 to 800
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         801 non-null    int64
 1   City               801 non-null    str
 2   Country            801 non-null    str
 3   Population (2024)  801 non-null    int64
 4   Population (2023)  801 non-null    int64
 5   Growth Rate        801 non-null    float64
dtypes: float64(1), int64(3), str(2)
memory usage: 37.7 KB

In [31]:
#find cities with population greater than 20 million
new_df=df[df["Population (2024)"]>20000000]["City"]
new_df

0          Tokyo
1          Delhi
2       Shanghai
3          Dhaka
4      Sao Paulo
5          Cairo
6    Mexico City
7        Beijing
8         Mumbai
Name: City, dtype: str

In [32]:
#find all cities in vetnam
Vietnam=df[df["Country"]=="Vietnam"] 
Vietnam

,Unnamed: 0,City,Country,Population (2024),Population (2023),Growth Rate
38,38,Ho Chi Minh City,Vietnam,9567656,9320866,0.0265
79,79,Hanoi,Vietnam,5431801,5253385,0.0340
272,272,Can Tho,Vietnam,1938915,1865172,0.0395
375,375,Hai Phong,Vietnam,1463650,1422974,0.0286
460,460,Da Nang,Vietnam,1253228,1220634,0.0267
508,508,Bien Hoa,Vietnam,1142997,1110824,0.0290

In [34]:
#find cities in china that are growing in population in (2024)
China=df[(df["Country"]=="China") & (df["Growth Rate"]>0)]["City"]

In [36]:
China

2              Shanghai
7               Beijing
10            Chongqing
18            Guangzhou
19              Tianjin
             ...
782             Jiamusi
790             Dongtai
791        Zhangjiagang
793    Xianyang Shaanxi
800           Panzhihua
Name: City, Length: 225, dtype: str

In [ ]:
#total popln of largest cities in india

India=df[df["Country"]=="India"]
total_pop=India["Population (2024)"].sum()
total_pop

np.int64(262676454)

In [41]:
India=df[df["Country"]=="India"]["Population (2024)"].sum()
India

np.int64(262676454)

In [42]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 801 entries, 0 to 800
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         801 non-null    int64
 1   City               801 non-null    str
 2   Country            801 non-null    str
 3   Population (2024)  801 non-null    int64
 4   Population (2023)  801 non-null    int64
 5   Growth Rate        801 non-null    float64
dtypes: float64(1), int64(3), str(2)
memory usage: 37.7 KB

In [46]:
#find cities experiencing growth decline and calculate growth median
decline=df[df["Growth Rate"]<0]["Growth Rate"].median()
decline

np.float64(-0.0019)

In [50]:
#find growing cities in  China and calculate the minimum population they had in 2023
growing=df[(df["Country"]=="China") &(df["Growth Rate"]>0)]["Population (2023)"].min()
growing

np.int64(733810)