In [1]:
import pandas as pd

student_df = pd.read_csv("student_survey_clean.csv")

In [2]:
student_df.head()

,gender,highschool_grade,study_year,faculty,ung_grade_2023,accomodation,allowance,scholarship,study_hours,party_week,drinks_night,missed_classes,failed_classes,in_relationship,parent_approve,relation_parent
0,Female,76.0,2nd Year,Arts & Social Sciences,72.0,Private accommodation/ stay with family/friends,R 4001- R 5000,No,8+,Only weekends,8+,3,0,Yes,Yes,Very close
1,Male,89.0,2nd Year,Economic & Management Sciences,75.0,Private accommodation/ stay with family/friends,R 7001 - R 8000,"Yes (NSFAS, etc...)",8+,Only weekends,3-5,4+,0,No,Yes,Very close
2,Male,76.0,1st Year,AgriSciences,55.0,Private accommodation/ stay with family/friends,R 4001- R 5000,No,3-5,2,8+,3,0,No,Yes,Very close
3,Male,89.0,2nd Year,Engineering,84.0,Private accommodation/ stay with family/friends,R 6001 - R 7000,No,3-5,3,8+,2,0,Yes,Yes,Very close
4,Female,74.0,2nd Year,Arts & Social Sciences,52.0,Private accommodation/ stay with family/friends,R 4001- R 5000,No,3-5,Only weekends,5-8,1,3,No,Yes,Fair

In [6]:
# Target or Features
X = student_df.drop("ung_grade_2023", axis =1 )
Y = student_df[["ung_grade_2023"]]

In [8]:
X.tail()

,gender,highschool_grade,study_year,faculty,accomodation,allowance,scholarship,study_hours,party_week,drinks_night,missed_classes,failed_classes,in_relationship,parent_approve,relation_parent
373,Male,85.0,Highschool,Arts & Social Sciences,Unknown,R 5001 - R 6000,No,3-5,Only weekends,3-5,0,0,No,Yes,Very close
374,Female,74.0,Highschool,Science,Private accommodation/ stay with family/friends,Unknown,No,3-5,3,1-3,0,0,No,Yes,Close
375,Female,73.0,2nd Year,Economic & Management Sciences,Private accommodation/ stay with family/friends,R 6001 - R 7000,"Yes (NSFAS, etc...)",5-8,1,8+,0,0,Yes,Yes,Very close
376,Male,85.0,Highschool,Economic & Management Sciences,Private accommodation/ stay with family/friends,R 4001- R 5000,No,1-3,4+,5-8,4+,0,No,Yes,Close
377,Female,80.0,1st Year,Economic & Management Sciences,Private accommodation/ stay with family/friends,R 5001 - R 6000,No,3-5,Only weekends,3-5,1,0,No,No,Close

In [ ]:
# Grouping Categories

In [ ]:
# Label Encoding

In [ ]:
# Normalization