In [6]:
import numpy as np
import pandas as pd
titanic_df=pd.read_csv("titanic_df_Ageoutlier.csv")

In [4]:
np.sign(-45)

np.int64(-1)

In [ ]:
titanic_df.drop("Unnamed: 0",axis=1,inplace=True)
#correlation
titanic_df.corr(numeric_only=True)

,PassengerId,Survived,PStatus,Age,SibSp,Parch,Fare
PassengerId,1.000000,0.029340,-0.035349,0.036847,-0.082398,-0.011617,0.009592
Survived,0.029340,1.000000,-0.359653,-0.077221,-0.017358,0.093317,0.268189
PStatus,-0.035349,-0.359653,1.000000,-0.369226,0.067247,0.025683,-0.554182
Age,0.036847,-0.077221,-0.369226,1.000000,-0.308247,-0.189119,0.096067
SibSp,-0.082398,-0.017358,0.067247,-0.308247,1.000000,0.383820,0.138329
Parch,-0.011617,0.093317,0.025683,-0.189119,0.383820,1.000000,0.205119
Fare,0.009592,0.268189,-0.554182,0.096067,0.138329,0.205119,1.000000

In [ ]:
import scipy.stats as stats

In [13]:
titanic_df.head(2)

,PassengerId,Survived,PStatus,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [15]:
contegency_table=pd.crosstab(titanic_df.PStatus,titanic_df.Survived)
contegency_table

Survived    0    1
PStatus
1          64  122
2          90   83
3         270   85

In [17]:
chi2_score,pvalue,dof,expected_frequency=stats.chi2_contingency(contegency_table)

In [23]:
print(f"Chi-Squared test score: {round(chi2_score,3)}")
print(f"P-value ={round(pvalue,5)}")

Chi-Squared test score: 92.901
P-value =0.0

In [20]:
pvalue

np.float64(6.709861749756909e-21)

In [36]:
contegency_table=pd.crosstab(titanic_df.SibSp,titanic_df.Survived)
contegency_table

Survived    0    1
SibSp
0         296  175
1          86   97
2          14   11
3           8    4
4          15    3
5           5    0

In [37]:
chi2_score,pvalue, _,_=stats.chi2_contingency(contegency_table)

In [38]:
print(f"Chi-Squared test score: {round(chi2_score,3)}")
print(f"P-value ={round(pvalue,5)}")

Chi-Squared test score: 22.068
P-value =0.00051